'use client';

// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from 'next/link';
import {createContext, useContext, useEffect, useState } from 'react';
import { useRouter } from 'next/navigation';

import { me, logout } from '../lib/auth';
import { UserContext } from "./UserContext";

const inter = Inter({ subsets: ["latin"] });

const navMenu = [
  { route: '/', name: 'Top' },

];

type User = {
    id: number;
    name: string;
    email: string;
};

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

console.log("layout render");
    const router = useRouter();
    const [user, setUser] = useState<User | null>(null);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        const checkAuth = async () => {
            try {
                const response = await me();

                if (response.ok) {
                    const data = await response.json();
                    if (data.user) {
                        setUser(data.user);
                    }
                }
                else {

                }    
                console.log('layout-user:', user);

            } catch (error) {
                console.error(
                    '認証確認失敗',
                    error
                );

                //router.replace('/login');
            } finally {
                setLoading(false);
            }
        };

        checkAuth();
    }, [router]);



    const handleLogout = async () => {
        try {
            await logout();
            setUser(null);
        } catch (error) {
            console.error(
                'ログアウト失敗',
                error
            );
        }

        router.replace('/');
        router.refresh();
    };

  return (
    <html lang="ja-JP" className="dark">
      <body className="font-sans antialiased dark:text-gray-400 dark:bg-black">
        <div className="min-h-screen bg-gray-100 dark:bg-black">
       
          <header className="border-b flex items-center h-14 px-4">
            <div className="hidden space-x-8 sm:-my-px sm:ms-10 sm:flex">
              {navMenu.map((menu, index) => (
                <Link href={menu.route} key={index}>
                    {menu.name}
                </Link>
              ))}
            </div>

            <div className="ml-auto">
              
              {user ? (
                <button
                  className="text-sm text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-300"
                  onClick={handleLogout}
                >
                  Logout
                </button>
              ) : (
                <Link
                  href="/login"
                  className="text-sm text-gray-500 dark:text-gray-400 hover:text-gray-700 dark:hover:text-gray-300"
                >
                  Login
                </Link>
              )}
            </div>


          </header>

            <main>
              <div className="py-3">
                  <div className="mx-auto px-3 space-y-3">

                    <UserContext.Provider value={{user,setUser}}>
                      {children}
                    </UserContext.Provider>
                </div>
              </div>
            </main>
        </div>
      </body>
    </html>
  );
}
